//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woohoo.Agi.Engine.Interpreter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlayerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlayerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Woohoo.Agi.Engine.Interpreter.PlayerResources", typeof(PlayerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FontAmiga8x8 {
            get {
                object obj = ResourceManager.GetObject("FontAmiga8x8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FontAppleIIgs8x8 {
            get {
                object obj = ResourceManager.GetObject("FontAppleIIgs8x8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FontAtariST8x8 {
            get {
                object obj = ResourceManager.GetObject("FontAtariST8x8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FontEga8x8 {
            get {
                object obj = ResourceManager.GetObject("FontEga8x8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FontHercules16x16 {
            get {
                object obj = ResourceManager.GetObject("FontHercules16x16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FontUnknown8x8 {
            get {
                object obj = ResourceManager.GetObject("FontUnknown8x8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       Select a game to play.
        /// </summary>
        internal static string GameSelectionHeader {
            get {
                return ResourceManager.GetString("GameSelectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game found..
        /// </summary>
        internal static string GameSelectionNoGameFound {
            get {
                return ResourceManager.GetString("GameSelectionNoGameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\n\n({1} of {2}) ESC to cancel.
        /// </summary>
        internal static string HintMessageFormat {
            get {
                return ResourceManager.GetString("HintMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hints are currently unavailable..
        /// </summary>
        internal static string HintsNotAvailable {
            get {
                return ResourceManager.GetString("HintsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hints not found for this game. Please add the .hnt file to the game folder..
        /// </summary>
        internal static string HintsNotFound {
            get {
                return ResourceManager.GetString("HintsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hints.
        /// </summary>
        internal static string HintsTitle {
            get {
                return ResourceManager.GetString("HintsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to            ENTER COMMAND\n\n.
        /// </summary>
        internal static string InputBox {
            get {
                return ResourceManager.GetString("InputBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string InventoryAppleIIgs {
            get {
                return ResourceManager.GetString("InventoryAppleIIgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are carrying:.
        /// </summary>
        internal static string InventoryCarrying {
            get {
                return ResourceManager.GetString("InventoryCarrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nothing.
        /// </summary>
        internal static string InventoryNothing {
            get {
                return ResourceManager.GetString("InventoryNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the desired item..
        /// </summary>
        internal static string InventoryStatusForItemsAtariST {
            get {
                return ResourceManager.GetString("InventoryStatusForItemsAtariST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ENTER to select, ESC to cancel.
        /// </summary>
        internal static string InventoryStatusForItemsPC {
            get {
                return ResourceManager.GetString("InventoryStatusForItemsPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a key to return to the game.
        /// </summary>
        internal static string InventoryStatusNoItemsAmiga {
            get {
                return ResourceManager.GetString("InventoryStatusNoItemsAmiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press RETURN to continue..
        /// </summary>
        internal static string InventoryStatusNoItemsAtariST {
            get {
                return ResourceManager.GetString("InventoryStatusNoItemsAtariST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a key to return to the game.
        /// </summary>
        internal static string InventoryStatusNoItemsPC {
            get {
                return ResourceManager.GetString("InventoryStatusNoItemsPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n  {0} v{1}  \n\n.
        /// </summary>
        internal static string KernelVersion1 {
            get {
                return ResourceManager.GetString("KernelVersion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nName: {0}\nVersion: {1}\nId: {2}\nPlatform: {3}\nInterpreter: {4}\n.
        /// </summary>
        internal static string KernelVersion2 {
            get {
                return ResourceManager.GetString("KernelVersion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - {0}.
        /// </summary>
        internal static string ListBoxItemFormat {
            get {
                return ResourceManager.GetString("ListBoxItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOO LONG.
        /// </summary>
        internal static string ListBoxItemTooLong {
            get {
                return ResourceManager.GetString("ListBoxItemTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string ListBoxScrollbarDown {
            get {
                return ResourceManager.GetString("ListBoxScrollbarDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string ListBoxScrollbarDownHidden {
            get {
                return ResourceManager.GetString("ListBoxScrollbarDownHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        internal static string ListBoxScrollbarUp {
            get {
                return ResourceManager.GetString("ListBoxScrollbarUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string ListBoxScrollbarUpHidden {
            get {
                return ResourceManager.GetString("ListBoxScrollbarUpHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message too verbose:\n\n\&quot;{0}...\&quot;\n\nPress ESC to continue..
        /// </summary>
        internal static string MessageTooVerboseFormat {
            get {
                return ResourceManager.GetString("MessageTooVerboseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not now..
        /// </summary>
        internal static string NotNow {
            get {
                return ResourceManager.GetString("NotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (For example, \&quot;B:\&quot; or \&quot;C:\\savegame\&quot;).
        /// </summary>
        internal static string PathExample {
            get {
                return ResourceManager.GetString("PathExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game paused..
        /// </summary>
        internal static string PauseAmiga {
            get {
                return ResourceManager.GetString("PauseAmiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game paused..
        /// </summary>
        internal static string PauseAppleIIgs {
            get {
                return ResourceManager.GetString("PauseAppleIIgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game paused.  Press RETURN to continue..
        /// </summary>
        internal static string PauseAtariST {
            get {
                return ResourceManager.GetString("PauseAtariST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       Game paused.\nPress Enter to continue..
        /// </summary>
        internal static string PausePC {
            get {
                return ResourceManager.GetString("PausePC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agi Player.
        /// </summary>
        internal static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1.0.
        /// </summary>
        internal static string PlayerVersion {
            get {
                return ResourceManager.GetString("PlayerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string QuitButton {
            get {
                return ResourceManager.GetString("QuitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit the game, or continue?.
        /// </summary>
        internal static string QuitQueryAmiga {
            get {
                return ResourceManager.GetString("QuitQueryAmiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to leave the game..
        /// </summary>
        internal static string QuitQueryAtariST {
            get {
                return ResourceManager.GetString("QuitQueryAtariST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ENTER to quit.\nPress ESC to keep playing..
        /// </summary>
        internal static string QuitQueryPC {
            get {
                return ResourceManager.GetString("QuitQueryPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string RestartButton {
            get {
                return ResourceManager.GetString("RestartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the game?.
        /// </summary>
        internal static string RestartQueryAmiga {
            get {
                return ResourceManager.GetString("RestartQueryAmiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the game?.
        /// </summary>
        internal static string RestartQueryAppleIIgs {
            get {
                return ResourceManager.GetString("RestartQueryAppleIIgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to restart the game..
        /// </summary>
        internal static string RestartQueryAtariST {
            get {
                return ResourceManager.GetString("RestartQueryAtariST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ENTER to restart\nthe game.\n\nPress ESC to continue\nthis game..
        /// </summary>
        internal static string RestartQueryPC {
            get {
                return ResourceManager.GetString("RestartQueryPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No saved game is available..
        /// </summary>
        internal static string RestoreNoGameAvailable {
            get {
                return ResourceManager.GetString("RestoreNoGameAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no games to\nrestore in\n\n {0}\n\nPress ENTER to continue..
        /// </summary>
        internal static string RestoreNoGamesInFolderFormat {
            get {
                return ResourceManager.GetString("RestoreNoGamesInFolderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         RESTORE GAME\n\nOn which disk or in which directory is the game that you want to restore?\n\n{0}\n\n.
        /// </summary>
        internal static string RestorePathPromptFormat {
            get {
                return ResourceManager.GetString("RestorePathPromptFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ENTER to restore game.\nPress ESC to cancel..
        /// </summary>
        internal static string RestoreQuery {
            get {
                return ResourceManager.GetString("RestoreQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the arrow keys to select the game which you wish to restore. Press ENTER to restore the game, ESC to not restore a game..
        /// </summary>
        internal static string RestoreSelectSlot {
            get {
                return ResourceManager.GetString("RestoreSelectSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to describe this saved game?\n\n.
        /// </summary>
        internal static string SaveDescriptionPrompt {
            get {
                return ResourceManager.GetString("SaveDescriptionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Sorry, this disk is full.\nPosition pointer and press ENTER\n    to overwrite a saved game\nor press ESC and try again \n    with another disk\n.
        /// </summary>
        internal static string SaveDiskFull {
            get {
                return ResourceManager.GetString("SaveDiskFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game saved..
        /// </summary>
        internal static string SaveDone {
            get {
                return ResourceManager.GetString("SaveDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no directory named\n {0}\nPress ENTER to try again.\nPress ESC to cancel..
        /// </summary>
        internal static string SavePathDoesNotExistFormat {
            get {
                return ResourceManager.GetString("SavePathDoesNotExistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          SAVE GAME\n\nOn which disk or in which directory do you wish to save this game?\n\n{0}\n\n.
        /// </summary>
        internal static string SavePathPromptFormat {
            get {
                return ResourceManager.GetString("SavePathPromptFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ENTER to save game.\nPress ESC to cancel..
        /// </summary>
        internal static string SaveQuery {
            get {
                return ResourceManager.GetString("SaveQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the arrow keys to move\n     the pointer to your name.\nThen press ENTER\n.
        /// </summary>
        internal static string SaveRestoreSelectName {
            get {
                return ResourceManager.GetString("SaveRestoreSelectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the arrow keys to select the slot in which you wish to save the game. Press ENTER to save in the slot, ESC to not save a game..
        /// </summary>
        internal static string SaveSelectSlot {
            get {
                return ResourceManager.GetString("SaveSelectSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score:%d of %d.
        /// </summary>
        internal static string ScoreStatusNew {
            get {
                return ResourceManager.GetString("ScoreStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score: %d of %d.
        /// </summary>
        internal static string ScoreStatusOld {
            get {
                return ResourceManager.GetString("ScoreStatusOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectButton {
            get {
                return ResourceManager.GetString("SelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        internal static string SoundOff {
            get {
                return ResourceManager.GetString("SoundOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        internal static string SoundOn {
            get {
                return ResourceManager.GetString("SoundOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound:%s.
        /// </summary>
        internal static string SoundStatusNew {
            get {
                return ResourceManager.GetString("SoundStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound is %s.
        /// </summary>
        internal static string SoundStatusOld {
            get {
                return ResourceManager.GetString("SoundStatusOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d: eval.%d.
        /// </summary>
        internal static string TraceFunctionNumber {
            get {
                return ResourceManager.GetString("TraceFunctionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  :%c.
        /// </summary>
        internal static string TraceFunctionResult {
            get {
                return ResourceManager.GetString("TraceFunctionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string TraceFunctionResultFalse {
            get {
                return ResourceManager.GetString("TraceFunctionResultFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string TraceFunctionResultTrue {
            get {
                return ResourceManager.GetString("TraceFunctionResultTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string TraceParameterEnd {
            get {
                return ResourceManager.GetString("TraceParameterEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string TraceParameterSeparator {
            get {
                return ResourceManager.GetString("TraceParameterSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d.
        /// </summary>
        internal static string TraceParameterSigned {
            get {
                return ResourceManager.GetString("TraceParameterSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string TraceParameterStart {
            get {
                return ResourceManager.GetString("TraceParameterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %u.
        /// </summary>
        internal static string TraceParameterUnsigned {
            get {
                return ResourceManager.GetString("TraceParameterUnsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d: cmd.%d.
        /// </summary>
        internal static string TraceProcedureNumber {
            get {
                return ResourceManager.GetString("TraceProcedureNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return.
        /// </summary>
        internal static string TraceProcedureReturn {
            get {
                return ResourceManager.GetString("TraceProcedureReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d: %s.
        /// </summary>
        internal static string TraceProcedureText {
            get {
                return ResourceManager.GetString("TraceProcedureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ==========================.
        /// </summary>
        internal static string TraceSeparatorLine {
            get {
                return ResourceManager.GetString("TraceSeparatorLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose word.
        /// </summary>
        internal static string TypelessBox {
            get {
                return ResourceManager.GetString("TypelessBox", resourceCulture);
            }
        }
    }
}
