//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woohoo.Agi.Detection {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Databases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Databases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Woohoo.Agi.Interpreter.Detection.Databases", typeof(Databases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;us-ascii&quot;?&gt;
        ///&lt;database&gt;
        ///  &lt;config&gt;
        ///    &lt;includes&gt;
        ///      &lt;pattern name=&quot;OBJECT&quot; /&gt;
        ///      &lt;pattern name=&quot;WORDS.TOK&quot; /&gt;
        ///      &lt;pattern name=&quot;*VOL.*&quot; /&gt;
        ///      &lt;pattern name=&quot;*DIR&quot; /&gt;
        ///      &lt;pattern name=&quot;DIRS&quot; /&gt;
        ///    &lt;/includes&gt;
        ///    &lt;excludes /&gt;
        ///  &lt;/config&gt;
        ///  &lt;games&gt;
        ///    &lt;game name=&quot;AGI Demo 1&quot; platform=&quot;PC&quot; date=&quot;XXXX-XX-XX&quot; version=&quot;&quot; format=&quot;&quot; interpreter=&quot;2.425&quot; language=&quot;English&quot; comments=&quot;&quot;&gt;
        ///      &lt;file name=&quot;OBJECT&quot; crc32=&quot;05853ab3&quot; md5=&quot;60175f87421161f368e39de8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Agi {
            get {
                return ResourceManager.GetString("Agi", resourceCulture);
            }
        }
    }
}
